// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	DeleteAllFeedbacks(ctx context.Context) error
	GetAllFeedbacks(ctx context.Context) ([]Feedback, error)
	InsertFeedback(ctx context.Context, message string) (Feedback, error)
}

var _ Querier = (*Queries)(nil)
